### ISSUE TITLE
Add support for Twilio Video Android 6.0.0

### ISSUE THREAD

**Issue by 4brunu** [dkornev/TwilioVideoXamarinAndroid#13]
Hey,

First of all, thanks for this Xamarin binding for Twilio Video Android.

Could you please update the binding to support the Twilio Video Android 6.0.0?
https://www.twilio.com/docs/video/changelog-twilio-video-android-v6

Thanks

**Comment by guillermo-gerard** [comment]
Hi @4brunu 
I have another repository where I've done the binding to 6.2.0 
You can found it here: https://github.com/guillermo-gerard/Twilio.Video.Android.Xamarin.Binding 

Having said that, you must be aware that you can find some conflicts if you are using more than one twilio binding (for example, if you use the one mentioned above, with twilio voice from this repository)
If that is your case, you can wait a couple of days to see if Denis decides to merge my pull request #15

**Comment by 4brunu** [comment]
Hi @guillermo-gerard, great work, thanks 👍
By the way, are you also planing to update the iOS version?
https://github.com/dkornev/TwilioVideoXamarinIOS

**Comment by guillermo-gerard** [comment]
I've done a couple of bindings for iOS in the past, but I'm more an Android guy  :)
In top of that and more importantly: I don't even have a mac at hand to do the build process. I've used a remote machine a friend allows me to use sometimes but it is a real pain, and I do it only if I'm forced to do it (for work, or something like that)

**Comment by 4brunu** [comment]
ok ok, thanks for the reply 🙂

**Comment by dkornev** [comment]
Thank you for your contribution @guillermo-gerard . I've updated the binding to v6.2.1.
@4brunu Let me know which binding you want me to update next.
