### ISSUE TITLE
Cannot build Android project

### ISSUE THREAD

**Issue by denfast** [dkornev/TwilioVideoXamarinAndroid#2]
Iv'e included the 4.3.1 package in to my android project but I ma getting the build error:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java/lang/String;)V :  invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

 Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.twilio.video.Camera2Capturer.switchCamera:(Ljava/lang/String;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.twilio.video.Camera2Capturer$1.onCameraError:(Ljava/lang/String;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.twilio.video.Camera2Capturer$3.onCameraSwitchDone:(Z)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in com.twilio.video.CameraCapturer.updateCameraParameters:(Lcom/twilio/video/CameraParameterUpdater;)Z: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.EglRenderer.init:(Lorg/webrtc/EglBase$Context;[ILorg/webrtc/RendererCommon$GlDrawer;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.PeerConnectionFactory.setVideoHwAccelerationOptions:(Lorg/webrtc/EglBase$Context;Lorg/webrtc/EglBase$Context;)V: invoking a static interface method org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.SurfaceTextureHelper.<init>:(Lorg/webrtc/EglBase$Context;Landroid/os/Handler;)V: invoking a static interface method org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;[I)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.VideoDecoderWrapper.createDecoderCallback:(J)Lorg/webrtc/VideoDecoder$Callback;: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.VideoEncoderWrapper.createEncoderCallback:(J)Lorg/webrtc/VideoEncoder$Callback;: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Translation has been interrupted
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
    	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:365)
    	at com.android.dx.command.dexer.Main.runDx(Main.java:286)
    	at com.android.dx.command.dexer.Main.main(Main.java:244)
    	at com.android.dx.command.Main.main(Main.java:95)
    Caused by: java.lang.InterruptedException: Too many errors
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)

**Comment by dkornev** [comment]
What's your android SDK version?  It can be checked in a manifest file.
Also, please check your _TargetFrameworkVersion_ for your Android project, it should be set to _v9.0_.

I would also recommend updating VS your using to the latest version.
Let me know if it helps.

**Comment by denfast** [comment]
> What's your android SDK version? It can be checked in a manifest file.
> Also, please check your _TargetFrameworkVersion_ for your Android project, it should be set to _v9.0_.
> 
> I would also recommend updating VS your using to the latest version.
> Let me know if it helps.

This is my setup:
Visual Studio Community 2019 for Mac
Version 8.2.5 (build 5)
Xamarin.Android
Version: 9.4.1.0 (Visual Studio Community)
Android SDK: 8.1 (API level 27)
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 28.0.3

I've changed Android compile version from 9.0 to 8.1 (Target Framework) and was able to build after that.  Thank you for your help.

**Comment by sauravchaudhary94** [comment]
Hi denfast,
I am also facing the same issue after updating the package. I tried changing version to 8.1 but It is giving same erroe again. Can you please help me with that?

**Comment by dkornev** [comment]
@denfast FYI

According to https://stackoverflow.com/questions/48532610/is-java-8-features-available-for-xamarin-android-in-java-binding-project we need to set d8 to enable Java 8 feature.

I created a Xamarin Android project from the default template added Twilio.Video.Android.XamarinBinding NuGet package enabled d8 and managed to build the project successfully.

**Comment by denfast** [comment]
@dkornev The d8 option fixed my problem
