### ISSUE TITLE
Build Error: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

### ISSUE THREAD

**Issue by sauravchaudhary94** [dkornev/TwilioVideoXamarinAndroid#3]
Have you added STUN/TURN server adding while connecting audio/video in your Xamarin Binding?
If Yes May you please help me with some explanation regarding this? I already have created Video / audio call using your earlier binding. But Now some private network issue is there so need to add that STUN/Turn server configuration also.

**Comment by dkornev** [comment]
Hi.
Unfortunately, personally I didn't set up STUN/TURN for our application, but as I see we have _ROOM TYPE_ set to _Peer-to-peer_ and _TURN_ option enabled. What kind of problem do you have? Is it an SDK issue? Please send me logs or an error message if it is. Or just let me know more details about your issue.

**Comment by sauravchaudhary94** [comment]
Hi,
I updated the TwilioBinding to 4.1.3 and I got the below issue while building the project:
"Error: java/lang/String;)V : invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13) "
I tried to change sdk-version to 26 or 27  above issue didn't get resolved.
If you can help with this issue how to resolve it will be a great help.

**Comment by dkornev** [comment]
https://github.com/dkornev/TwilioVideoXamarinAndroid/issues/2
It looks very similar to me.
Please take a look and let me know if it helps

**Comment by sauravchaudhary94** [comment]
I changed version to Android 8.0.1 but still same issue is coming. May you please check?

**Comment by dkornev** [comment]
1. Please try to update VS for mac and update all the build tools in the SDK manager.
2. Let me know your setup.
3. If you're using Linker make sure it doesn't link the Twilio SDK.
4. If you're using Proguard make sure that you've added correct progruard setting.

My .csproj configs:
`...`

**Comment by sauravchaudhary94** [comment]
1. Visual studio I am using is latest : Visual studio for mac community edition(8.2.6 build(26)).
2. Manifest is <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />.
3. I was using Relinker.Droid for earlier twilio.video , I have removed that.
4. Updated the configuration of CSProj File according to yours.

After updating all this I am getting this error now:
Error: Compilation can't be completed because some library classes are missing.  

In File and Path It is showing R8.

**Comment by dkornev** [comment]
Please attach more details about the error.

Also sometimes manual cleaning up _obj_ and _bin_ folders helps for me

**Comment by sauravchaudhary94** [comment]
library of d8 and r8 which we have introduced in AndroidDexTool and AndroidLinkTool is not getting found.
![image](https://user-images.githubusercontent.com/13644659/65064958-17924480-d99f-11e9-8446-8d37ffddd5ce.png)

**Comment by dkornev** [comment]
I tried to use the NuGet package with an empty Xamarin Android project template and got the same error. I managed to fix this with changing _TargetFrameworkVersion_ to _v8.1_, but it works with _v9.0_ in our production application.

Will continue to investigate it

**Comment by sauravchaudhary94** [comment]
Okay, If you find some workaround please post it here .

**Comment by dkornev** [comment]
According to https://stackoverflow.com/questions/48532610/is-java-8-features-available-for-xamarin-android-in-java-binding-project we need to set _<AndroidDexTool>d8</AndroidDexTool>_ to enable Java 8 feature.

I created a Xamarin Android project from the default template added _Twilio.Video.Android.XamarinBinding_ NuGet package enabled _<AndroidDexTool>d8</AndroidDexTool>_ and managed to build the project successfully.

@sauravchaudhary94 please this solution and let me know if it works for you

**Comment by sauravchaudhary94** [comment]
@dkornev  Tried adding that in debug as well as release but I am getting below error:
![image](https://user-images.githubusercontent.com/13644659/65172006-cf8c2400-da69-11e9-96cb-7c3a0c7de893.png)

not getting compiled successfully.

**Comment by sauravchaudhary94** [comment]
below is my csproj configuration in debug or release mode:

![image](https://user-images.githubusercontent.com/13644659/65172147-1e39be00-da6a-11e9-919c-4052d7f793ad.png)

**Comment by dkornev** [comment]
Try to enable_d8_ and disable _r8_.

Try to build a new Xamarin Android application from a template with _d8_ and this NuGet package

**Comment by sauravchaudhary94** [comment]
Can you please briefly tell that how to enable this r8 or d8. Actually I don't have idea about that where to enable it.

**Comment by dkornev** [comment]
Android project options -> Android Build -> set _Dex Compiler_ to _d8_ and _Code Shrinker_ to _None_ (if you don't use it)
<img width="531" alt="Screen Shot 2019-09-18 at 11 05 05 AM" src="https://user-images.githubusercontent.com/16318669/65173761-5efeec00-da04-11e9-8711-fc706f5cf9c2.png">

**Comment by sauravchaudhary94** [comment]
Already It set to d8.

![image](https://user-images.githubusercontent.com/13644659/65174220-124ffb00-da6e-11e9-9bf8-c6476d229e03.png)

**Comment by dkornev** [comment]
Try to build a new Xamarin Android application from a template with d8 and this NuGet package and let me know the result

**Comment by sauravchaudhary94** [comment]
I have created fresh Xamarin.Android Project and set d8 thing. And Yes it is getting compiled.
But why this is happening in forms. Is there any compatibility problem with Xamarin.Forms?

**Comment by sauravchaudhary94** [comment]
Can you try once like first adding 2.2.1 and after that 4.3.1 maybe that might be creating problem. I didn't check though .

**Comment by dkornev** [comment]
I didn't find any reasons of that and it doesn't seem to be a binding issue.

**Comment by dkornev** [comment]
I think that the original issue with the binding is already fixed. (Setting Dex Compiler to d8 helped).
Closing this
