### ISSUE TITLE
In Room.IListener there is no  onDominantSpeakerChanged()   present in the interface .

### ISSUE THREAD

**Issue by sylendra7** [dkornev/TwilioVideoXamarinAndroid#4]
Hi ,

In Room.IListener there is no  onDominantSpeakerChanged()   present in the interface .
https://www.twilio.com/docs/video/detecting-dominant-speaker

Can you please tell me how to get this , if I implementing Room.IListener I'm getting following methods but onDominantSpeakerChanged() is missed . Because based on the dominant speaker change I want to display the dominant speaker video .

   public void OnConnected(Room p0)
        {
            throw new NotImplementedException();
        }

        public void OnConnectFailure(Room p0, TwilioException p1)
        {
            throw new NotImplementedException();
        }

        public void OnDisconnected(Room p0, TwilioException p1)
        {
            throw new NotImplementedException();
        }

        public void OnParticipantConnected(Room p0, RemoteParticipant p1)
        {
            throw new NotImplementedException();
        }

        public void OnParticipantDisconnected(Room p0, RemoteParticipant p1)
        {
            throw new NotImplementedException();
        }

        public void OnReconnected(Room p0)
        {
            throw new NotImplementedException();
        }

        public void OnReconnecting(Room p0, TwilioException p1)
        {
            throw new NotImplementedException();
        }

        public void OnRecordingStarted(Room p0)
        {
            throw new NotImplementedException();
        }

        public void OnRecordingStopped(Room p0)
        {
            throw new NotImplementedException();
        }

**Comment by sylendra7** [comment]
Hi @dkornev 
 
Any update on this ...? Can you please help me ... ? 


-- Kind Regards
Sylendra

**Comment by dkornev** [comment]
Hi @sylendra7

**Comment by sylendra7** [comment]
Hi @dkornev ,

Can you please tell me how to make that as public in the MetaData.xml file like a piece of code...?
I tried with other version .aar file also but I'm getting the build errors ... If you provide the line of code then I can add it .

--Kindly Regards
Sylendra

**Comment by sylendra7** [comment]
Hi @dkornev , 

Any help regarding this...? 


THanks & Regards
Sylendra

**Comment by dkornev** [comment]
Fixed in v4.3.1.1
NuGet package will be updated soon (in 10 - 30 minutes)

**Comment by sylendra7** [comment]
Hi @dkornev  thanks for the update .


--Kind Regards
Sylendra
