### ISSUE TITLE
Add support for Twilio Video Android 5.0.0

### ISSUE THREAD

**Issue by 4brunu** [dkornev/TwilioVideoXamarinAndroid#5]
Hey, 

First of all, thanks for this Xamarin binding for Twilio Video Android.

Could you please update the binding to support the Twilio Video Android 5.0.0?
https://www.twilio.com/docs/video/changelog-twilio-video-android#500-october-23rd-2019

Thanks

**Comment by dkornev** [comment]
Thanks for creating this. I'll try to put it on my schedule

**Comment by dkornev** [comment]
Updated to v5.8.1.
The NuGet package will be available soon.

**Comment by 4brunu** [comment]
Thanks 👍
